apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
data:
  config-override.json: |
    {
      "events": "ws://game-server:8080/events",
      "camera": "ws://rtsp-server:8080/stream"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game-client
  name: game-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-client
  template:
    metadata:
      labels:
        app: game-client
    spec:
      containers:
      - name: game-client
        image: atgracey/game-ui-client:latest
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: game-client
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: game-client
