apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    env: test
  name: robot-hand-control
  namespace: akri
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      env: test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: test
    spec:
      affinity: {}
      containers:
      - args:
        - -c
        - while true; do echo "testing"; sleep 120; done
        command:
        - /bin/sh
        image: mak3r/rps-gestures:0.0.9
        imagePullPolicy: IfNotPresent
        name: container-0
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev
          name: devices
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev
          type: ""
        name: devices
        